---
name: Docker

on:
  push:
    branches: [ "main" ]
    tags: [ '*' ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata for tag
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          annotations: |
            org.opencontainers.image.title=NPO/CHP5 kaniko 
            org.opencontainers.image.description=An extension of kaniko-project/executor that contains some script for deploying maven projects to CHP5 @ NPO
            org.opencontainers.image.vendor=MMProgrami
          labels: |
            org.opencontainers.image.title=NPO/CHP5 kaniko l
            org.opencontainers.image.description=An extension of kaniko-project/executor that contains some script for deploying maven projects to CHP5 @ NPO l
            org.opencontainers.image.vendor=MMProgrami
          tags: |
            type=ref,event=branch
            type=ref,event=tag
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          annotations: ${{ steps.meta.outputs.annotations }}

     
